### ISSUE TITLE
Add selection by name

### ISSUE THREAD

**Issue by guillaume-chevalier** [chakki-works/chakin#6]
Instead of `chakin.download(number=CHAKIN_INDEX, ...`

I'd like something like `chakin.download(name="GloVe.840B.300d", ...`

**Comment by guillaume-chevalier** [comment]
Nice

**Comment by icoxfog417** [comment]
@Hironsan Please update PYPI package whenever you like or can (version number is already updated).

**Comment by guillaume-chevalier** [comment]
The README.md could also be updated with new instructions.
