### ISSUE TITLE
suggestion: download more than one set of word vectors

### ISSUE THREAD

**Issue by davidsbatista** [chakki-works/chakin#8]
for instance by passing a list:

`chakin.download(number=[11,12,13,14], save_dir='./')`

**Comment by icoxfog417** [comment]
Is downloading multiple word vectors so frequent? I want to consider it on demand from its needs.

**Comment by davidsbatista** [comment]
I usually, when setting up a new machine for experiments, get GoogleNews, GloVe and fasttext.

**Comment by icoxfog417** [comment]
Thank you for your reply. I discussed with @Hironsan and decided not to support this feature. 
Because we can execute list download by simple for loop.

```py
vector_ids = [11, 12, ...]
for i in vector_ids:
   chakin.download(number=i, save_dir="./")
```

```py
[chakin.download(number=i) for i in vector_ids]
```
